### ISSUE TITLE
rock: class names from sdk/lang/types hard coded in source code

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1007]
If we want to move / rename classes from these files we first need to deal with hard coded paths and class names in rock sources.

**Comment by marcusnaslund** [comment]
I would prefer to move most (or all) files if possible at once, otherwise we have to force people to update rock every other day.

**Comment by marcusnaslund** [comment]
As an update: Only four files remain. They cannot be moved right now.

**Comment by marcusnaslund** [comment]
- References to `lang_array` in `source/rock/backend/cnaughty/CGenerator.ooc` and `source/rock/middle/Type.ooc`
- One reference to `lang_String` in `source/rock/backend/cnaughty/Skeleton.ooc`
- References to `lang_types` in `source/rock/backend/cnaughty/CastWriter.ooc`, `source/rock/backend/cnaughty/CGenerator.ooc`, `source/rock/backend/cnaughty/ClassDeclWriter.ooc`, `source/rock/backend/cnaughty/FunctionCallWriter.ooc`, `source/rock/middle/FuncType.ooc`,

**Comment by marcusnaslund** [comment]
Moved to #1278
