### ISSUE TITLE
Implement class holding WaitCondition and Mutex

### ISSUE THREAD

**Issue by emilwestergren** [magic-lang/ooc-kean#1043]
Since a `Mutex` is always needed when using a `WaitCondition`, we might as well create a class for this.

Name suggestions so far:
* `SynchronizationLock`
* `WaitLock`
* `BlockLock`
* `MutexCondition`

The interface is the same as for `WaitCondition`, i.e.
`signal`
`broadcast`
`wait`

@sebastianbaginski @simonmika @marcusnaslund 
Let's reach a decision here and then someone can implement it.

**Comment by sebastianbaginski** [comment]
I think `lock` and `unlock` will have to be in public interface too as sometimes you want to wait only after testing a condition protected by the mutex.

**Comment by sebastianbaginski** [comment]
As for the name definitely `BlockLock`, as this one is a very unique name :)

**Comment by emilwestergren** [comment]
Yes, you're right, unless we can hide this instead.
```ooc
wait: func (condition: Func -> Bool)
```

**Comment by simonmika** [comment]
I suggest that what today is called `Mutex` should be called a `Lock` and that the combination of a mutex and wait condition is called a `WaitLock`. They should all have the same API though. We will then end up width:

- [ ] `Lock` - Abstract base class.
- [ ] `UnsafeLock` - Dummy not performing any locking.
- [ ] `SafeLock` - Uses regular mutex.
- [ ] `GlobalLock` - Uses one global lock for all locking.
- [ ] `RecursiveLock` - Can be locked multiple times by the same thread.
- [ ] `WaitLock` - Implements a more efficient wait method.

**Comment by simonmika** [comment]
Moving it all to `kean/concurrent` would be great while we are at it.

**Comment by simonmika** [comment]
And start using `free(Owner Receiver)` for closures.

**Comment by emilwestergren** [comment]
But `WaitLock` will be the only one with `signal`, `broadcast` and `wait` ?

**Comment by simonmika** [comment]
No, but it might offer the most efficient implementation. And I'm not sure about including `signal` and `broadcast` in the api at all.

**Comment by emilwestergren** [comment]
So how do you suggest the signaling of the lock is done?

**Comment by simonmika** [comment]
Can you provide a use case?

**Comment by emilwestergren** [comment]
Thread 1:
```ooc
while (!completed)
  waitLock wait()
```

Thread 2:
```ooc
complete()
completed = true
//Wake up thread 1 in some way...
```

Or did you mean `lock/unlock` will replace `wait/signal` for a `WaitLock`?

**Comment by simonmika** [comment]
Does thread 2 have the lock or not?

**Comment by emilwestergren** [comment]
Yes, normally thread 2 would call something like:
```ooc
waitLock signal()
```
which would wake up Thread 1

**Comment by simonmika** [comment]
Can a signal be automatically fired every time we lock up the lock?

**Comment by sebastianbaginski** [comment]
Sometimes the lock is used to protect the code section which checks for the waited condition, and after that we want to signal only if condition is met.

**Comment by simonmika** [comment]
So all locks should then have `wait` _and_ `signal`?

**Comment by emilwestergren** [comment]
Also, there is a reason why both `signal` and `broadcast` exist. Sometimes you want to wake all waiting threads and sometimes only one.

**Comment by simonmika** [comment]
There should probably be a `signal` and a `signalAll`. I kind of prefer calling it `signalAll` is the relation to `signal` is clearer this way.

**Comment by sebastianbaginski** [comment]
In some SDKs it is called `wake / wakeOne` and `wakeAll`.

**Comment by simonmika** [comment]
`wake` and `wakeAll` is good.

**Comment by marcusnaslund** [comment]
As an update, `WaitCondition` and `Thread` are now in `source/concurrent`, and `Mutex` (which is used in `base`) is in `source/system`.

**Comment by marcusnaslund** [comment]
@erikhagglund - what is left to do here?

**Comment by erikhagglund** [comment]
I have added the class WaitLock. According to the suggestions from Simon Mika above it is the refactoring of the existing Mutex-classes that needs to be done

**Comment by marcusnaslund** [comment]
> According to the suggestions from Simon Mika above it is the refactoring of the existing Mutex-classes that needs to be done

Are we doing that, though? @emilwestergren ?

**Comment by emilwestergren** [comment]
Maybe in the future, but I think @erikhagglund has done his part. We can keep the issue.

**Comment by marcusnaslund** [comment]
We keep the issue if something really is left to be done. If it's a *maybe* or *some day perhaps* then we might as well close it.

**Comment by emilwestergren** [comment]
Then close it

**Comment by sebastianbaginski** [comment]
The tittle of this issue is "Implement class holding WaitCondition and Mutex" and I think it is already fixed. Let's close it.
