### ISSUE TITLE
Rename AbstractContext to DrawContext

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1102]

**Comment by emilwestergren** [comment]
* `GraphicsContext`
* `DrawContext`

@simonmika @sebastianbaginski pick your favorite

**Comment by simonmika** [comment]
`DrawContext`

**Comment by sebastianbaginski** [comment]
I agree with Simon, someone might confuse the other one with `GraphicsContext` from Java:)

**Comment by emilwestergren** [comment]
Then the decision is mutual.
