### ISSUE TITLE
Change license to the MIT license

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1127]
Minor non-important detail, but we have license notices in some (most) files, but not all. The actual year in those vary a lot as well. The GPL states that `each file should have at least the “copyright” line and a pointer to where the full notice is found.`

We shouldn't do this manually as there are good tools for this, even in VSCode I believe.

**Comment by marcusnaslund** [comment]
Using `Atom`, this should do the trick:
https://atom.io/packages/auto-copyright

**Comment by thomasfanell** [comment]
Changing the year is not required I think. It should be sufficient to state the year the file was first created? While we're at this, should Simon stand as copyright holder still, or should we change to an organization? ping @simonmika

**Comment by simonmika** [comment]
The year should indicate the last _major_ change. That is what is important to copyright. Usually an interval is good for year.

**Comment by marcusnaslund** [comment]
We should also change license while we're at it.
