### ISSUE TITLE
Number types

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1143]
We currently have a whole lot of them besides `Int`. 

On one side we have `Short`,`Long` and `ULong`, and on the other side we find `Int16, Int64` with unsigned counterparts. Their respective memory representations are identical, but we've defined properties and methods very differently on them. Preserving both tracks seems very wasteful.

(As an example, `Short minimumValue` exists, but `Int16 minimumValue` does not).

**Comment by emilwestergren** [comment]
I prefer `Int64, Int32, Int16, Int8` since it's much more readable. `Long` can be 32-bit on some platforms and 64 on others (although guaranteed to be *at least* 32 bits).

**Comment by sebastianbaginski** [comment]
I agree with @emilwestergren but on the other hand @marcusnaslund has a good argument that the code is easier to write and is more "ooc-style" with simple `Long, Int, Short ...`.
We could also typedef our numeric types to the ones with known size, `Long == Int64`, `Int == Int32` etc.

**Comment by marcusnaslund** [comment]
> We could also typedef our numeric types to the ones with known size

Sounds good to me, or in some other way enforcing the sizes of these types.

We will also need to find a name for the eight-bit numeric type. Having `Int8` and `UInt8` doesn't look too good if we go with `Long` and `Short`.

**Comment by emilwestergren** [comment]
Why is `Short` easier to write than `Int16`? Also, `Long` already has a standard definition, I think it's not very good to use that name and create our own definition.

**Comment by sebastianbaginski** [comment]
For me it makes no difference, but I can imagine people less familiar with these things wondering should they use 16 or 32 bit.
As for `Long`, C standard states that it should be at least 32 bits, so 64 bits works fine here ;)

**Comment by marcusnaslund** [comment]
> Why is Short easier to write than Int16?

I wouldn't say it's easier to write, but I do think it's more along the ooc style.

**Comment by emilwestergren** [comment]
If you wonder whether to use 16 or 32, wouldn't you wonder whether to use `short` or `int` anyway? ;)

That's my point, you will look at a `Long` in ooc and you can't be *sure* it is 64-bit according to the C standard. So how can I make sure it's 64-bit? `Long Long`? No, you don't have to to that here in ooc because we decided `Long` is always 64-bit.

**Comment by marcusnaslund** [comment]
> you can't be sure it is 64-bit according to the C standard

I don't think that matters - `ooc` may transpile to `c`, but it is its own language.

**Comment by emilwestergren** [comment]
> I don't think that matters - `ooc` may transpile to `c`, but it is its own language.

Yes, but the fact that `long` is *at least* 32-bit is pretty standard in any language.

**Comment by emilwestergren** [comment]
What I'm saying is, `long` has such a vague definition to begin with and only creates confusion. `Int64` is hard to misinterpret.

**Comment by marcusnaslund** [comment]
> pretty standard in any language

Well, C# defines `long` as always being 64 bits, and the underlying `.NET` type is `System::Int64`. That doesn't mean we should also do it that way, but it's not unprecedented.

**Comment by emilwestergren** [comment]
True, but you can still use `Int64` if you want to. I thought this issue was about choosing one of them?

**Comment by sebastianbaginski** [comment]
I think @simonmika will prefer the `Short, Int, Long` version, although when you write structures (/covers) which you want to expose in shared library it is better to use types with exact size, so you can make assumptions about memory layout and alignment, so I don't think we should get rid of them completely.

**Comment by emilwestergren** [comment]
`Long`
* More widely used
* Fits the ooc style better (according to some)

`Int64`
* The size is in the name - no reference lookup needed
* Platform agnostic

**Comment by simonmika** [comment]
Having common type names with numbers in them make them harder to pronounce and slightly harder to write. The keys are so far away from the home row that it is hard hit the right ones. Seriously who can write `Int64` without glimpsing at the keyboard and without mistyping regularly.

I suggest defining the types in a platform agnostic way even when c doesn't do it.

**Comment by simonmika** [comment]
For clarity let us call the different naming ideas _conventional_ and _descriptive_. Let us also define them as below:

Integers
-------------
size | signed | conventional | descriptive
---|---|---|---
8 | no | `Byte` | `UInt8`
8 | yes | `SByte` | `Int8`
16 | no | `UShort` | `UInt16`
16 | yes | `Short` | `Int16`
32 | no | `UInt` | `UInt32`
32 | yes | `Int` | `Int32`
64 | no | `ULong` | `UInt64`
64 | yes | `Long` | `Int64`
128 | no | `ULLong` | `UInt128`
128 | yes | `LLong` | `Int128`

Floating Point
-------------
total size | significand size | conventional | descriptive
---|---|---|---
32 | 24 | `Float` or ` Single`  | `Float32`
32 | 24 | `Double` | `Float64`

**Comment by sebastianbaginski** [comment]
> Seriously who can write Int64 without glimpsing at the keyboard

Typically I just type `int...` and hit Ctrl+Space for auto-completion :)

I think you have mistyped 32 instead of 64 in the last column for floating point.

**Comment by marcusnaslund** [comment]
@simonmika Do you mean we should go with the conventional names, but that they build on the descriptive types so that they have fixed size? Should the descriptive names be allowed in ooc at all?

**Comment by emilwestergren** [comment]
Also, do we really want to break the consistency by using `Byte/SByte` instead of `Byte/UByte` ? I know it's like this in C# for example, just asking questions.

**Comment by simonmika** [comment]
@marcusnaslund: I agree.

@emilwestergren: A byte is unsigned as is a char in c. Doing it backwards would be very confusing.

**Comment by simonmika** [comment]
@sebastianbaginski: That is my point, you need to move your hands farther away.

**Comment by marcusnaslund** [comment]
Fixed by #1257
