### ISSUE TITLE
How to handle memory allocations

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1205]
The current system needs to be revised.
EDIT: Updated with decision which has been made.

- [x] **The `gc_` prefix is outdated and should be removed.**
#1201 aims at doing just that.

- [x] **We should decide whether we want the names as they appear in C (`malloc`, `calloc`, ...) or something more ooc-ish (`allocate`, `allocateZero`, ...).**
We will keep the `C` names and instead use `Buffer` everywhere, with better names. `gc_free` is renamed to `memfree`.

- [x] **Debugging functionality by adding a print statement upon allocation and free.**
Once we use `Buffer` everywhere, this is easy to add manually, and will not be part of upstream.

- [x] **The use of `gc_malloc` is hard-coded into rock (yay).**
We either just keep it in `Memory.ooc` (easiest solution), or search-replace everywhere in rock. The latter solution might create other type of errors.

 **Use the `sdk/Buffer` class for direct memory allocations.**
Separate issue: #763 

- [x] **We never actually make sure that `malloc` and others actually return something. They *may* return `null` if allocation fails. We should handle this, maybe right in our allocation routine.**
We will handle this with a `safe` flag in our `Buffer` class.

**Comment by davidpiuva** [comment]
Maybe `allocateFast`, `allocateZero`, ...

I have been trying to hold a debug list of all allocations in use for assertions around crashes. If a call crashes then I might want to check that `this` is a valid allocation and not freed memory, null or another type. If we have our own allocator then this can be made easy.

**Comment by sebastianbaginski** [comment]
> Wouldn't it make more sense to add your own special routines for that (which call malloc etc.) and change those specific allocation calls?

Yes, but sometimes you can't even know which subset of allocations is interesting, as a double-free bug can result in a crash in another module at runtime, so in fact you need to check each allocation / deallocation.

> They may return null if allocation fails. We should handle this, maybe right in our allocation routine.

That's true, but what can we do in that case. Throwing exception is not guaranteed to work, as it needs to allocate dynamic memory, as well as printing something on terminal :) Exit program with a specific exit code ?

**Comment by marcusnaslund** [comment]
> in fact you need to check each allocation / deallocation.

Alright, that makes sense. We can hide that in version blocks then. But I don't like having to through an extra step (such as `gc_malloc`) every time something is allocated.

> Throwing exception is not guaranteed to work, as it needs to allocate dynamic memory

Yes, but allocating an insane amount of memory might fail, but the amount needed to throw an exception is probably always available.

**Comment by marcusnaslund** [comment]
Can we do something like this? We introduce a version flag `-DdebugMemory`:
```ooc
version (!debugMemory) {
    malloc: extern func (SizeT) -> Pointer
    free: extern func (Pointer)
    // etc. etc.
} else {
    _malloc: extern (malloc) func (SizeT) -> Pointer
    malloc: func (size: SizeT) -> Pointer {
        result := _malloc(size)
        "allocated %p" printfln(result)
        result
    }
    _free: extern (free) func (Pointer)
    free: func (pointer: Pointer) {
        "freeing %p" printfln(result)
        _free(pointer)
    }
```
That way, we don't always get an unneccessary function call for each allocation/free.

**Comment by davidpiuva** [comment]
Optimal performance is the only way.

**Comment by marcusnaslund** [comment]
> Optimal performance is the only way.

Is that your approval? :)

**Comment by davidpiuva** [comment]
If you can make it work without crashing in malloc.

**Comment by tatoon187** [comment]
![image](https://github.com/user-attachments/assets/70b7f528-3aad-4b9c-bc84-051ba34b54cc)
