### ISSUE TITLE
Rename source/sdk to source/system

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1206]
As I recall, we want to do this, right @simonmika @sebastianbaginski ?

~~I tried this, and it just works out of the box. I did not expect rock to be so flexible.~~

**Comment by simonmika** [comment]
Did you chance the name of the use file?

**Comment by simonmika** [comment]
And did you do `rock -x`?

**Comment by marcusnaslund** [comment]
Yeah, sorry, I was celebrating a bit to early. It doesn't work after `rock -x`. Too bad. :(

**Comment by marcusnaslund** [comment]
Moved to #1278
