### ISSUE TITLE
Instead of TVectorList, simply extend VectorList<T>

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1208]
For example, `VectorList<Float>` has no special parts to it (like adding two elements or getting the sum, but `FloatVectorList` has.

We currently have:

- [ ] `FloatVectorList`
- [ ] `IntVectorList`
- [ ] `FloatComplexVectorList`
- [ ] `BoolVectorList`
- [ ] `FloadEuclidTransformVectorList`
- [ ] `FloatPoint2DVectorList`

I feel this convention is slowly getting out of hand, and is in the long run inconsistent. How would one know to use `FloatPoint2DVectorList` instead of `VectorList<FloatPoint2D>`? Why doesn't `FloatPoint3DVectorList` exist? And so on.

What's worse is, we're not consistent even with these types. We sometimes use `IntVectorList`, sometimes `VectorList<Int>`, and likewise with the others. If you want to pass one type along to a function which expects the other, you have to explicitly cast, meaning you have to create a *new* `VectorList`. Furthermore, the extra classes also mean unnecessary extra code to maintain, albeit a small amount. 

By instead just extending `VectorList<Float>`, for example, instead of deriving a completely new class, all of the confusion is gone, and I see no negative effects. Can anyone tell me why we shouldn't do this?

**Comment by niklasborwell** [comment]
I'm not sure why we did it like this in the first place, but I agree that it would be much better with a simple extension, if it works as expected.

**Comment by marcusnaslund** [comment]
Maybe I should actually try something before ranting about it... :) 

Methods (seem to) work fine, but I run into trouble with properties and operators... maybe @thomasfanell or @fredrikbryntesson knows more about the limitations of extending generic classes. If someone wants to give it a try, my attempt on `FloatComplexVectorList` is available at https://github.com/marcusnaslund/ooc-kean/tree/extendvl

**Comment by marcusnaslund** [comment]
**Correction!** Methods *and* properties both work, I was just not careful enough. 

The problem is with operators, they fail with `error Expected or function declaration`.

We can solve this by implementing the operators directly in `VectorList`, with something like

```ooc
operator + (other: This<T>) -> This<T> {
		minimumCount := this count < other count ? this count : other count
		result := This<T> new(minimumCount)
		match T {
			case Double => for (i in 0 .. minimumCount) { result add((this[i] as Double) + (other[i] as Double)) }
			case Float => //etc. etc. etc.
		}
		result
	}
```
I've tried and it works. This seems perfectly acceptable to me. We have very few operators defined on the `*VectorList` classes and this will reduce overall line count *and* removes the confusion noted above.

**Comment by davidpiuva** [comment]
I remember that we had performance problems with memcpy being called without inline for each array access to generics. By having FloatVectorList, the memory duplication could then know the type in compile time and become faster.

**Comment by marcusnaslund** [comment]
This will have to wait for future versions of rock where bugs with `interface` and `template` have been taken care of.
