### ISSUE TITLE
Abstract shared contexts in OpenGLContext

### ISSUE THREAD

**Issue by emilwestergren** [magic-lang/ooc-kean#1256]
Currently the user needs to manage and create an `OpenGLContext` for each thread where it is used. This could be abstracted by internally creating a new shared backend context for every new thread which uses the `OpenGLContext` (or in practice we want a `register` function since we want all context creation in the `VidhanceContext` constructor).

Each backend context can then hold instances of everything that is needed to maintain thread safety, like default shaders.

Since not every OpenGL resource can be shared between contexts, these need special care. This is the case for Framebuffer Objects (used when rendering to a texture), Vertex Array Objects, Pixel Buffer Objects. This means these need special consideration when recycled and reused in different threads.

@davidpiuva @sebastianbaginski please give me your opinions since it will probably be one of you who implements this

**Comment by davidpiuva** [comment]
Being able to create GPU resources without having to pass a context would be nice but having a pointer passed to function calls is a way to make sure that a context exists before we create things.

**Comment by sebastianbaginski** [comment]
Let's list some cases affected by having multiple threads working in the graph (filter A and filter B are running in different threads TA / TB), maybe it will be easier to think about good solution then:
- A wants to render on image, it calls `image canvas` and a FBO is created in thread TA
- frame propagates to filter B, control switches to thread TB
- B wants to render, but it can't use the same FBO as it was created in TA
- B needs to use own opengl context to create FBO in thread TB, is that right ?

I was thinking about having a base class for thread-aware resources, something like (don't mind the names and lack of obvious mutex locks)
```ooc
ThreadedResource: class {
    HashMap<ThreadID, VectorList<This> >: static perThreadResources
    threadAffinity : ThreadID
    new: static func (some parameters) -> This {
        if (This->perThreadResources[thisThreadId] isEmpty == false && check parameters)
            return this->perThreadResources takeFirst()
        return This new(parameters) // also sets threadAffinity
    }
    free: override func {
        This perThreadResources[thisThreadId] << this
    }
    checkThreadAffinity: func -> Bool {
          this threadAffinity == thisThreadID()
    }
}
```
I think you get the idea.
And then use it as base class for resources that must be recycled in correct threads:
```ooc
FrameBufferObject: abstract class extends ThreadedResource {
}

PixelBufferObject: abstract class extends ThreadedResource {
}
```

So we could have the recycling logic in one place.

**Comment by davidpiuva** [comment]
It seems like Sebastian has more experience with multi threading on the CPU.

**Comment by emilwestergren** [comment]
That looks good to me @sebastianbaginski

**Comment by sebastianbaginski** [comment]
In fact the FBO backend in canvas is the only problem I'm able to spot now, but I have not written a single line of opengl code we use now. What else can go wrong in current data flow through the graph ? Shader programs needs to be compiled per-thread as well ?

**Comment by emilwestergren** [comment]
You are right, FBO is currently the only one creating problems but we should at least keep the others in mind when we do this implementation.

`ShaderProgram` is actually a shared resource I believe, however since we have some default shaders which can be used by several threads I think we want these to be bound to the thread as well.

**Comment by davidpiuva** [comment]
Can we reuse the GPU part of the shader and have different interfaces to the CPU or would that only make it slower?

**Comment by davidpiuva** [comment]
@emilwestergren Can we close this now?

**Comment by emilwestergren** [comment]
Sure
