### ISSUE TITLE
Fixture expect printouts no longer works

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1265]
`expect(3, is equal to(4))`
> -> : expected  equal to  '', was ''

@marcusnaslund can you reproduce

**Comment by marcusnaslund** [comment]
Even better: `expected  equal to  '�.i', was '�.i'`

**Comment by marcusnaslund** [comment]
Could be, but hopefully isn't, related to the number system switch.

**Comment by sebastianbaginski** [comment]
OK, so this is about wrong formatting placeholders ?

**Comment by marcusnaslund** [comment]
It seems like we should only use `%`. I will try.

**Comment by marcusnaslund** [comment]
Wait, `"%i %f" printfln(3, 4.2f)` works just fine. So there's something wrong with `Fixture` itself.

**Comment by thomasfanell** [comment]
I got similar results before, and that turned out to be ownership issues with `Text`. In my particular case I solved it by taking ownership `take()`. I haven't scanned through this particular code path, but it could be worth some consideration.

**Comment by marcusnaslund** [comment]
In `Fixture createFailureMessage` where I messed up a test comparing ints:

`(leftValue as Cell<Int>) val toString() println()` works
`(leftValue as Cell) toString() println()` prints nonsense

**Comment by sebastianbaginski** [comment]
It looks like a weird error with type resolution in Cell, it works when I replaced toString in Cell with this
```
toString: func -> String {
		result: String
		if (T inheritsFrom?(Text))
			result = (this val as Text) toString()
		else if (T inheritsFrom?(Bool))
			result = (this val as Bool) toString()
		else if (T inheritsFrom?(Char))
			result = (this val as Char) toString()
		else if (T inheritsFrom?(Int))
			result = (this val as Int) toString()
		else if (T inheritsFrom?(Long))
			result = (this val as Long) toString()
		else if (T inheritsFrom?(LLong))
			result = (this val as LLong) toString()
		else if (T inheritsFrom?(UInt))
			result = (this val as UInt) toString()
		else if (T inheritsFrom?(ULong))
			result = (this val as ULong) toString()
		else if (T inheritsFrom?(ULLong))
			result = (this val as ULLong) toString()
		else if (T inheritsFrom?(Float))
			result = "%.8f" formatFloat(this val as Float)
		else if (T inheritsFrom?(Double))
			result = "%.12f" formatDouble(this val as Double)
		else if (T inheritsFrom?(LDouble))
			result = "%.12f" formatLDouble(this val as LDouble)
		else
			raise("[Cell] toString() is not implemented on the specified type")
		result
	}
```

similar bug to the infamous red screen, it was caused by a weird syntax in match as well

**Comment by sebastianbaginski** [comment]
Maybe it stopped working when we updated rock recently ?

**Comment by marcusnaslund** [comment]
@fredrikbryntesson ?

**Comment by fredrikbryntesson** [comment]
I found the bad guy. 
https://github.com/magic-lang/ooc-kean/commit/22c0475babf8d0038b4aa46c252eacd7455f8098

In `sdk/lang/types.ooc` we changed:
`case => raise("[Cell] toString() is not implemented on the specified type")` to 
`case => raise("[Cell] toString() is not implemented on the specified type"); null`.

**Comment by fredrikbryntesson** [comment]
Oh I missed Sebastians fix. Sorry.

**Comment by marcusnaslund** [comment]
Yeah, I was mostly tagging you because

> Maybe it stopped working when we updated rock recently ?
