### ISSUE TITLE
Refactoring blend in canvas (GPU)

### ISSUE THREAD

**Issue by davidpiuva** [magic-lang/ooc-kean#1281]
Emil wants to get rid of Blend in Canvas because it was a temporary solution.
Supporting full alpha filtering with YUVA images would be overkill and defeat the original purpose of cleaning up but we can't just get rid of blending because we need to draw text and logotypes.

* One way to get rid of blend is to draw all sprites to a black image and then mix with the old image to produce a new image. This does not allow the sprites to overlap, will take more time and produces more code in total.
* Another way is to just move the blend property to the source image. This will not work with multiple input images since blending is performed on the shader's result based on all input images.

**Comment by davidpiuva** [comment]
Any ideas?

**Comment by emilwestergren** [comment]
I suggest we simply support drawing RGBA to YUV like this:
```ooc
yuv draw(rgba)
```
@sebastianbaginski what do you think?

**Comment by sebastianbaginski** [comment]
Isn't this implemented in Raster classes already ?
If you are asking about GPU, then I have no idea of what already works and what does not, better ask @davidpiuva

**Comment by davidpiuva** [comment]
Maybe we just have to start making shaders that take RGBA as input and have an easy to use conversion matrix with documentation about how to use it. Using the default shader would not make the conversion.

**Comment by davidpiuva** [comment]
https://github.com/magic-lang/ooc-kean/pull/1449 covers the old implementation with blend states. When a new way is implemented, alpha filtering can be added as another mode next to additive blending.

**Comment by marcusnaslund** [comment]
Fixed by #1709
