### ISSUE TITLE
Suspicious code in Vector2D

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1304]
In `resize` function, both branches of the `if` are the same:
```ooc
if (newRowCount > this rowCount && newColumnCount > this columnCount)
	temporaryResult = calloc(newRowCount * newColumnCount, T size)
else
	temporaryResult = calloc(newRowCount * newColumnCount, T size)
```
@marcusnaslund @tomasmahlberg

**Comment by tomasmahlberg** [comment]
I think before one was malloc and one was calloc but this was changed to this redundant code in some clean-up. You can safely remove the if statement and just keep `temporaryResult = calloc(newRowCount * newColumnCount, T size)`.

**Comment by tomasmahlberg** [comment]
Actually I guess you could just remove the explicit type declaration and change it to `temporaryResult := calloc(newRowCount * newColumnCount, T size)`. But you could probably figure that out by yourself. :)

**Comment by marcusnaslund** [comment]
Yes, @tomasmahlberg is right, it's my fault. Let's go with just the `calloc` version.

**Comment by sebastianbaginski** [comment]
OK, thanks.
@tomasmahlberg I though so too, but when I changed to `temporaryResult := calloc(newRowCount * newColumnCount, T size)` I got a segmentation fault :( Changing to `temporaryResult: T* = calloc(newRowCount * newColumnCount, T size)` seems to work...

**Comment by marcusnaslund** [comment]
I guess you have to explicitly say it's a `T` pointer, otherwise the pointer arithmetic later on won't work?

**Comment by sebastianbaginski** [comment]
Could be :)
