### ISSUE TITLE
`wait` in Promise should accept TimeSpan instead of double

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1307]
to improve readability and get rid of ugly constants

**Comment by emilwestergren** [comment]
Yes, and other similar parameters as well.

**Comment by marcusnaslund** [comment]
What about the unmangled functions, for example `kean_concurrent_promise_waitWithTimeout`? Should `TimeSpan` only be used internally?

**Comment by sebastianbaginski** [comment]
`kean_base_timeSpan` (I really don't like these names...) is already exported in the public API, we might as well just continue with it. I don't mind using it in API. @emilwestergren ?

**Comment by emilwestergren** [comment]
Sure
