### ISSUE TITLE
SynchronizedResource test fails sometimes

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1328]
Brings back old `ThreadPoolTest` memories.

**Comment by sebastianbaginski** [comment]
First I will try to minimize this to 4 threads and well see how it goes.

**Comment by sebastianbaginski** [comment]
https://github.com/magic-lang/ooc-kean/issues/1328

**Comment by marcusnaslund** [comment]
I will close this in a few days if I see no more problems.
