### ISSUE TITLE
Try / catch causes segmentation fault on windows

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1341]
Even when no exception is thrown

**Comment by sebastianbaginski** [comment]
It works on windows when using Exceptions without ThreadLocal variables.

**Comment by marcusnaslund** [comment]
> It works on windows when using Exceptions without ThreadLocal variables.

All the more reason to get rid of them.

**Comment by sebastianbaginski** [comment]
99,999% sure it works now as ThreadLocal is now gone. I will reopen if it happens again.
