### ISSUE TITLE
test.sh crashes on win32

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1342]
I guess due to https://github.com/magic-lang/ooc-kean/issues/1341

**Comment by marcusnaslund** [comment]
Still problems on Windows?

**Comment by sebastianbaginski** [comment]
I don't really know. The windows computer I used for testing was updated with new system and I haven't had the opportunity to test it since then.
I will do that as soon as I'm back from the leave (next thursday) or just someone else can check it.

**Comment by sebastianbaginski** [comment]
I think we can close this for now. It does not crash anymore as it fails to compile some test sources.
I will open new issues.
