### ISSUE TITLE
Version block from linux prevents linking gdi32 on windows

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1343]
ui.use:
```
version(windows)
	Libs: -lgdi32
version(linux)
	Libs: -lX11
```
does not work, -lgdi32 is not added to linker parameters.
Removing the linux version block works though:
```
version(windows)
	Libs: -lgdi32
```

Following  @thomasfanell  suggestion I tried also with 
```
version(windows) {
	Libs: -lgdi32
} else {
	Libs: -lX11
}
```
but this crashes compiler:
>magic-lang rock compiler
>Parsing...
>[lang/Backtrace] No backtrace extension nor execinfo - use a debugger!
>[Exception in Stack]: Trying to peek an empty stack.

**Comment by marcusnaslund** [comment]
Maybe it's a better idea to make a list using the `- [ ] description` syntax in #1334 rather than making one issue for each part.

**Comment by sebastianbaginski** [comment]
I was hoping that someone could help me with this one, you or / and @thomasfanell maybe ?
