### ISSUE TITLE
Take care of _RecycleBin

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1374]
The class in `source/draw/gpu/opengl/_RecycleBin.ooc` has a terrible name, but the underscore is there so that it does not conflict with the newer `source/concurrent/RecycleBin.ooc`. We should fix this, obviously.

- [ ] `OpenGLContext`
- [ ] `AndroidContext`

**Comment by emilwestergren** [comment]
The use of it in `OpenGLContext` should be replaced with the new generic `RecycleBin`. I tried this before but ran into problems due to problems in rock with ooc generics. Feel free to try this but make sure it is well-tested.

**Comment by emilwestergren** [comment]
Also, `AndroidContext` has some recycling of `EGLBgra` images which should be replaced with use of `RecycleBin`.

**Comment by davidpiuva** [comment]
`EGLBgra` will be replaced by `EGLRgba` in https://github.com/magic-lang/ooc-kean/pull/1422.
