### ISSUE TITLE
RGBA/BGRA confusion

### ISSUE THREAD

**Issue by emilwestergren** [magic-lang/ooc-kean#1384]
* Our entire API only supports BGRA
* OpenGL ES 3 only supports RGBA
* Everything seems to work in spite of this

We need some structure here. Which formats should be supported in the API? How come it actually works? What happens if we actually try to render RGBA instead of BGRA?

@davidpiuva @sebastianbaginski

**Comment by sebastianbaginski** [comment]
> What happens if we actually try to render RGBA instead of BGRA?

You get a bluish output like we did on windows few months ago, as winapi expected RGBA images.

As for the API, it does not make any difference for me, as long as we keep it consistent (BGR, row major order, is default in OpenCV though).

**Comment by davidpiuva** [comment]
I see no reasons to stick with BGR weirdness.

**Comment by ziquanyu** [comment]
When I was trying to connect opencv face detection with ooc.
I've read use `RasterBgra new(file)` to read in an image and send the pointer of this image to openCV.
But OpenCV got wrong color on it's own window, red and blue were switched.

**Comment by marcusnaslund** [comment]
Will someone (perhaps @davidpiuva since you're working on it currently) make a short simple list of what needs to be done for BGRA to be removed and this issue to be resolved?

**Comment by davidpiuva** [comment]
ok

**Comment by davidpiuva** [comment]
All changes are up as pull requests.

**Comment by davidpiuva** [comment]
All changes are merged. BGR is history.
