### ISSUE TITLE
Vulkan

### ISSUE THREAD

**Issue by davidhesselbom** [magic-lang/ooc-kean#1401]
Hey guys, I figured you might want to read this, if you haven't already:
https://developer.qualcomm.com/blog/introducing-vulkan-explicit-control-over-graphics-acceleration

**Comment by marcusnaslund** [comment]
Nice of you to drop by. :)

**Comment by davidhesselbom** [comment]
Eh, you know, I was in the area...

**Comment by davidpiuva** [comment]
The Vulkan specification would be just as good as DirectX if it were not for `VkDescriptorImageInfo` that has sampler states tied to texture views. They broke backward compatibility with OpenGL but did not fix the weird sampler limitation.

**Comment by marcusnaslund** [comment]
I will close this now as it's not a "proper issue", but thanks for the notice and feel free to drop by again!

**Comment by davidhesselbom** [comment]
Sure, a "proper issue" would have read something like 
> Now that Vulkan has been released and QualComm are actively promoting it, it's probably worth looking into using it instead of OpenGL ES. As mentioned by QualComm, this should bring significant performance and/or power usage improvements (e.g. support for tiled rendering architecture GPUs like Adreno to take full advantage of this _bandwidth saving techique_ [my italics]), less confusion caused by different implementations on Android and PC, etc. etc."

I was hoping this would all be evident by reading QualComm's own article, though... Anyway, I just wanted to bring this to your attention and didn't know how else to do it :)
