### ISSUE TITLE
Correct enum values in GpuImage.ooc

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1403]
```ooc
GpuImageType: enum {
	monochrome
	rgba
	rgb
	bgr
	bgra
	uv
	yuvSemiplanar
	yuvPlanar
	yuv422
}
```
should they start with upper case ? @marcusnaslund @emilwestergren

**Comment by marcusnaslund** [comment]
Yes. `GpuImageType` together with `Order` are the only exceptions.
Also, `TextureType` have almost the same elements and they start with upper case.
