### ISSUE TITLE
Define fill in Draw API

### ISSUE THREAD

**Issue by emilwestergren** [magic-lang/ooc-kean#1410]
Currently `fill` uses the color of the `Pen` associated with the `Canvas`. What about passing the color as a parameter instead?

`fill: func (color: ColorRgba)`

@sebastianbaginski @davidpiuva

**Comment by davidpiuva** [comment]
Makes sense since that is how my own engine works.

**Comment by emilwestergren** [comment]
Then we only use the `Pen` for lines, points etc?

**Comment by davidpiuva** [comment]
The pen should only be given as an argument when used to avoid side effects. If only one setting is used then just give that setting as an argument.

**Comment by emilwestergren** [comment]
So, something like this?
```ooc
fill: func (color: ColorRgba)
drawLines: func (points: VectorList<FloatPoint2D>, pen := Pen new())
drawPoints: func (points: VectorList<FloatPoint2D>, pen := Pen new())
```

**Comment by davidpiuva** [comment]
Maybe we don't even need the pen type.
```ooc
drawLines: func (points: VectorList<FloatPoint2D>, color := ColorRgba new(), width := 1.0f)
```

**Comment by sebastianbaginski** [comment]
I created this type in order to keep all the additional drawing parameters like line color, width, style, join type etc. in the future. We can discuss if this is really needed.

**Comment by marcusnaslund** [comment]
Fixed.
