### ISSUE TITLE
Implement fill for RasterCanvas

### ISSUE THREAD

**Issue by emilwestergren** [magic-lang/ooc-kean#1411]
When the API for `fill` has been decided in https://github.com/magic-lang/ooc-kean/issues/1410 then it would be nice to implement this for `Raster` classes.

@sebastianbaginski @davidpiuva

**Comment by davidpiuva** [comment]
We can do this after RGB has been merged since there are too many version conflicts with the same modules now.

**Comment by marcusnaslund** [comment]
`RGB` is in and `fill` has been implemented as #1410 is closed.
