### ISSUE TITLE
Static default colors in color covers

### ISSUE THREAD

**Issue by emilwestergren** [magic-lang/ooc-kean#1412]
`black ::= static ColorRgba new(0, 0, 0, 1)`
`white ::= static ColorRgba new(1, 1, 1, 1)`

would be nice. One problem is that `red/green/blue` are already members in `ColorRgba` so we can't define those default colors unless we change the naming.

@davidpiuva @marcusnaslund what do you think?

**Comment by davidpiuva** [comment]
I prefer hard coded rgb values without names. It keeps the codebase minimal and is easier to read. People usually mix up cyan, magenta, crimson and indigo with other colors anyway.

**Comment by marcusnaslund** [comment]
Having `ColorRgba black` mean one thing and `ColorRgba blue` be a completely different thing is terrible, so yes, *if* we do this, we need some better naming conventions.

**Comment by emilwestergren** [comment]
I don't agree that `ColorRgba new(1, 1, 0, 1)` is more readable than `ColorRgba yellow`. Let's start with the most basic colors. This is mostly used for debugging where you care more about having different colors than a specific RGB-value.

**Comment by marcusnaslund** [comment]
How about we rename the current `blue` etc. to `componentBlue` or `blueComponent`, and then add some basic colours like `blue` etc.?

**Comment by emilwestergren** [comment]
or simply `r, g, b, a` ?

**Comment by marcusnaslund** [comment]
Yeah, but one-letter variable names aren't pretty though.

**Comment by emilwestergren** [comment]
Already used in `ColorYuv`

**Comment by marcusnaslund** [comment]
It's settled, then.
Is `red`, `green`, `blue`, `yellow`, `white`, `black` good enough to start with?

**Comment by emilwestergren** [comment]
Yes

**Comment by marcusnaslund** [comment]
I'm on it.
