### ISSUE TITLE
Rename ClockTimer to CpuClockTimer

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1415]
What it really measures is the CPU usage for the process, it can cause confusion when used in multi-threaded environment.

**Comment by marcusnaslund** [comment]
Ah, very good.

Seems easy to do since `ClockTimer` isn't used in any other project. But `Timer` measures wall time? So I could imagine an abstract `Timer` class with `WallTimer` and `CpuTimer` derivations.

Related - I just noticed `Fixture` uses a `ClockTimer`. I guess it shouldn't?

**Comment by sebastianbaginski** [comment]
Yes I guess Fixture should use a regular `Timer`.

**Comment by marcusnaslund** [comment]
@fredrikbryntesson - thoughts?

**Comment by fredrikbryntesson** [comment]
If it is not walltime we should of course rename it, marcus idea with an abstract class is good but do we need it at the moment?

**Comment by marcusnaslund** [comment]
@fredrikbryntesson We are using both versions, if that's what you mean.

**Comment by marcusnaslund** [comment]
Here is my suggestion: https://github.com/magic-lang/ooc-kean/pull/1437
