### ISSUE TITLE
Global free~all function

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#1421]
We should have a single funciton that collects all cleanup code from kean

**Comment by marcusnaslund** [comment]
Hmm, but how to do this? We would need a new module which `use`s all other modules and calls all `free~all` that exist... right?

**Comment by sebastianbaginski** [comment]
Yes, basically something like this.
Alternative is to have
```ooc
SomeClass: class ... {
     free: static func ~all {
     ....
    }
    atexit(This free~all)
}

```
in each module to automatically register cleanup callbacks at program exit.
I think there is implementation defined upper limit on count of `atexit` callbacks. Also I don't think this is a good idea for shared library as the user might want to register his callbacks, or not use `atexit`at all.
Another idea to reverse the dependency (not having to include each module in the cleanup module, but rather include the cleanup module whenever it is needed and register a callback) is to implement `atexit` mechanism ourselves, by just keeping a collection of function pointers to be called one after another.

**Comment by marcusnaslund** [comment]
I don't think it should be done automatically for the same reason you specify, and because no other advanced memory management is performed automatically in this language.

**Comment by marcusnaslund** [comment]
OK, suggestion:

- We implement our own `atexit` equivalent somewhere in `system`, called `globalCleanup()` or whatever. All classes with a `free~all` function will register a pointer to that function there.
- Any project which uses kean can call our `globalCleanup()` upon exit which in turn calls all `free~all` listed.

@fredrikbryntesson @sebastianbaginski ?

**Comment by sebastianbaginski** [comment]
Sounds great.

**Comment by fredrikbryntesson** [comment]
Approve

**Comment by marcusnaslund** [comment]
Then I'm on it.

**Comment by marcusnaslund** [comment]
`GlobalCleanup` now exists, just need to make it useful before this issue is closed.
