### ISSUE TITLE
Render text

### ISSUE THREAD

**Issue by emilwestergren** [magic-lang/ooc-kean#1438]
It would be useful to be able to render text onto images.

@davidpiuva @sebastianbaginski

**Comment by davidpiuva** [comment]
To be fast enough, you have to upload a text buffer to the GPU and render from an atlas using a custom shader.

**Comment by sebastianbaginski** [comment]
I guess a texture with character atlas should do for basic uses. I also remember using FreeType for rendering text with OpenGL few years ago (I needed "fancy" fonts).

**Comment by emilwestergren** [comment]
Yes, and we don't want one render call per letter, but it's OK to start out that way and optimize it later.
