### ISSUE TITLE
RasterCanvasTest doesn't test if images are correctly drawn

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1442]
There should be some input images to compare with, presumably, unless it can be done algorithmically.

**Comment by sebastianbaginski** [comment]
Some of them could be, I remember drawing a simple color gradients or diagonal lines in some of these tests. I can look into it.

**Comment by davidpiuva** [comment]
Should raster drawing be implemented with DrawState first?

**Comment by sebastianbaginski** [comment]
I don't know, I guess it can wait. @marcusnaslund ?

**Comment by marcusnaslund** [comment]
Absolutely. `DrawState` for the win.

**Comment by marcusnaslund** [comment]
Fixed by #1746
