### ISSUE TITLE
PointerVector and PointerVectorList

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1474]
These classes lack tests, but are also not used anywhere. Are we going to use them? Have we ever used them? Should they be removed?

@sebastianbaginski @emilwestergren @fredrikbryntesson ?

**Comment by sebastianbaginski** [comment]
I vote for removal.

**Comment by emilwestergren** [comment]
I think they can be removed.

**Comment by fredrikbryntesson** [comment]
I think they were something davidh made as an experiment, they can have been used one time in some specific situation. But if they are dead now I guess it is safe to kill them.
