### ISSUE TITLE
Change most/all includes to imports

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1484]
For example, we should never do `include stdlib` but instead have an `stdlib.ooc` defined (and it already is!) and do `import stdlib`. This has the advantage of not having to add a certain include flag every time, and let's us define external functions just once. We already do this for some files, just need to make it consistent.

We don't need to do this for specific files only used once, but rather for headers included in many places.

- [x] pthread
- [x] windows
- [x] time
- [x] signal
- [x] unistd
- [x] ~~stdint~~
- [x] stdlib
- [x] errno

**Comment by marcusnaslund** [comment]
@thomasfanell - this was your idea, do you want to/do you have time to take it, or should I?

**Comment by thomasfanell** [comment]
I'll be very busy this week, but if you want we could split the burden?

**Comment by marcusnaslund** [comment]
I will get started when I get time and we'll see what's left next week. :)

**Comment by thomasfanell** [comment]
Sounds good

**Comment by marcusnaslund** [comment]
@sebastianbaginski @fredrikbryntesson I propose we create a folder in `system` where these `ooc`-files are placed. My suggestion is `external`. `imports` or `includes` would also work. Opinions? Suggestions?

**Comment by marcusnaslund** [comment]
Actually `imports` is a bad idea because then other files would have stuff like `import imports/windows`

**Comment by fredrikbryntesson** [comment]
`external` is the best imo. `imports` and `includes` becomes weird. `import includes/windows`, not good.

**Comment by marcusnaslund** [comment]
Well, this was easier than expected.
