### ISSUE TITLE
Mixup of coordinate systems in old draw API

### ISSUE THREAD

**Issue by davidpiuva** [magic-lang/ooc-kean#1490]
When using transforms in reference coordinates for scaling images (which is not allowed to begin with since it relies on pixel size), it makes sense to keep zero in the same place at the center since we gave the transform in reference coordinates. The old draw API was however half way into using local coordinates for all transforms for compatibility with CPU contexts so scaling between sizes was done like local coordinates but with reference coordinates. This makes no sense to use since it is neither reference coordinates nor local coordinates.

**Comment by davidpiuva** [comment]
@emilwestergren @niklasborwell Should we implement local coordinates in DrawState to support local behaviour all the way, let all callers use proper reference coordinates or go back and just make a local scaling function for legacy calls?

**Comment by emilwestergren** [comment]
I vote for reference coordinates

**Comment by davidpiuva** [comment]
Then I start adapting the old calls to get rid of the offset that is just confusing.

**Comment by davidpiuva** [comment]
This is no longer an issue because the last feature to adapt to DrawState will soon be replaced.
