### ISSUE TITLE
Apply per pixel transform in Draw API

### ISSUE THREAD

**Issue by emilwestergren** [magic-lang/ooc-kean#1491]
We need a solution where we can apply a 2D-transform to an image where there is a unique transform for each pixel. I'm thinking something like this:

```ooc
applyTransform: func (getTransform: Func (coordinates: IntPoint2D) -> FloatTransform2D)

//Dummy example:
image canvas applyTransform(|| FloatTransform2D identity)
```

@niklasborwell @davidpiuva

**Comment by davidpiuva** [comment]
How would we solve the inverse to get the texture coordinate for each pixel?
Mobile graphics hardware would force us to slowly pack 2x16 bits into 4x8 bits.

**Comment by emilwestergren** [comment]
The 2D-transform should be for the texture coordinates.
