### ISSUE TITLE
Add support for comparing relevant classes in unit test framework. 

### ISSUE THREAD

**Issue by niklasborwell** [magic-lang/ooc-kean#1500]
We need to be able to use the `is equal to` framework with all relevant classes.

Higher priority, i.e. used a lot:
- [x] FloatVector2D
- [x] FloatVector3D
- [x] FloatPoint2D
- [x] FloatPoint3D
- [x] Quaternion
- [x] FloatEuclidTransform
- [x] FloatRotation3D
- [x] FloatTransform2D
- [x] FloatTransform3D

Lower priority:
- [ ] FloatBox2D
- [ ] FloatConvexHull2D
- [ ] FloatShell2D
- [ ] IntBox2D
- [x] IntPoint2D
- [x] IntPoint3D
- [ ] IntShell2D
- [ ] IntTransform2D
- [x] IntVector2D
- [x] IntVector3D
- [ ] FloatComplex
- [ ] FloatMatrix

**Comment by niklasborwell** [comment]
@marcusnaslund

**Comment by marcusnaslund** [comment]
Would `FloatComplex` and `FloatMatrix` from `math` be suitable candidates, also?

**Comment by niklasborwell** [comment]
I guess so, but in the low priority category.

**Comment by marcusnaslund** [comment]
@niklasborwell I should have the high-priority items working before lunch tomorrow.

**Comment by niklasborwell** [comment]
Sounds great.

**Comment by marcusnaslund** [comment]
There we go. #1518 will take care of the remaining items.
