### ISSUE TITLE
CsvReader causes random double free or corruption errors.

### ISSUE THREAD

**Issue by niklasborwell** [magic-lang/ooc-kean#1511]
I was trying to parse some csv files and encountered a lot of double free or corruption errors.
I'm not 100% sure it's caused by the CsvReader since it's very difficult to debug a double free, but not using or replacing it with a FileReader fixed the issue.

The file used was in the format: 
```
header1, header2, header3, header4, header5, header6, header7, header8
0,-0.0252756,0.710025,0.702086,0.0479738,0.028104,0.132787,0.686439
1,-0.0264497,0.710073,0.702076,0.0467545,0.0286426,0.133369,0.686526
...
596,-0.0442818,0.71115,0.696035,0.0885445,-0.00810854,0.0652997,0.654637
```
and the first row was skipped (so not related to https://github.com/magic-lang/ooc-kean/issues/1494). Also the last row was checked for errors so not related to the fact that it might include an empty row after the last row in the file.
I wouldn't say this is a high priority since we have a file reader as a workaround.
@thomasfanell

**Comment by thomasfanell** [comment]
I am unable to reproduce this. Would you mind whipping up an example on how you are using it?

**Comment by niklasborwell** [comment]
That was a good idea. Unfortunately I just replaced the code with a FileReader. I can try to re-create it later.

**Comment by niklasborwell** [comment]
My previously working FileReader  version just started spitting out the same error..I'll investigate further and close or update this issue when I find the reason.

**Comment by niklasborwell** [comment]
It don't think this is related to any file reader after all. Closing.
