### ISSUE TITLE
Double check that correct tolerance values are passed to Fixture...

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1575]
...for all types. The `Quaternion` test fails with tolerance nan on windows, for example.

( @fredrikbryntesson @sebastianbaginski There is something to be said about testing on windows, it helps us detect bugs like these.)

**Comment by fredrikbryntesson** [comment]
Interesting point, maybe we should put a little focus on windows now and then?

**Comment by marcusnaslund** [comment]
I think that's been @sebastianbaginski 's point earlier, and I concur.

**Comment by fredrikbryntesson** [comment]
Ok, I surrender then. @sebastianbaginski allocate some quality time with our favourite Micro$oft product.

**Comment by marcusnaslund** [comment]
I might also take another look at the Windows build when I have some time if @sebastianbaginski is busy with other stuff.

**Comment by sebastianbaginski** [comment]
I think we both should do it, preferably using two different Win$ versions.

**Comment by marcusnaslund** [comment]
Dibs on Windows 3.1 :)
