### ISSUE TITLE
Move stdio to system/external

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1586]
Make an ooc wrapper file for stdio.h and put it in external.

**Comment by marcusnaslund** [comment]
Nope, ooc won't allow it. Nice.

**Comment by sebastianbaginski** [comment]
What happened here ? :)

**Comment by marcusnaslund** [comment]
Haha, had a good idea but the sometimes fixed compilation order wouldn't allow it. Maybe I could make the entire `system/IO.ooc` into the file I want, hm.

**Comment by marcusnaslund** [comment]
Bah, I will reopen and see if I can find a better approach later.
