### ISSUE TITLE
Add readFromFile and writeToFile feature to HashMap

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1720]
With a new and functioning HashMap as of #1717 we will also need to implement files for reading from and writing to file. An example use case:

```ooc
map := HashMap readFromFile("data.txt")

box := FloatBox2D parse(map get("myboxdata"))
values := map get("a list") split(",")
doSomeCalculation(values[0] toFloat(), values[5] toFloat())
```

**Comment by sebastianbaginski** [comment]
Wouldn't it require a custom serialization methods for user types ?

**Comment by marcusnaslund** [comment]
This will just be for <String, String>/<Text, Text> maps, and the user will have to do the parsing (which with toString/toText and parse in at least the geometry classes will be quite straight-forward. We can also do `split` on the strings to get `VectorList<String>` for different keys.

**Comment by sebastianbaginski** [comment]
Alright.

**Comment by marcusnaslund** [comment]
For now, anyway, we can extend it for other types later if we want/need to.
