### ISSUE TITLE
Remove Text

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1724]
Yes. 

Since string literals don't leak anymore, and since people are mostly just confused by how `Text` ownership works, there is no need for `Text`. Right now we just have a lot of duplicate code with `toString` and `toText` in tons of classes.

We've also caused a lot of confusion for ourselves, where for example the `filename` arguments to `FileWriter` and `FileReader` are different, one of them expects a `String`, the other a `Text`...

We can do the major breaking changes during the summer when most people are on holiday.

Thoughts, objections? @sebastianbaginski @thomasfanell @fredrikbryntesson @emilwestergren @davidpiuva ?

EDIT: It's decided. Here is what to do.

- [x] `source/uri`
- [x] `DateTime` and `TimeSpan`
- [x] `Cell` (and its extensions)
- [x] `source/unit`
- [x] `source/math`
- [x] `source/geometry` (breaks API)
- [x] `source/draw` (breaks API)
- [x] `CsvReader` and `CsvWriter` (breaks API)
- [x] `ArgumentParser` (breaks API)
- [x] `TextBuilder`
- [x] Any other minor uses
- [ ] Remove `Text`, `TextBuffer`

**Comment by emilwestergren** [comment]
I've never even used `Text` anyway so it's fine by me.

**Comment by davidpiuva** [comment]
Great! Caller should be the owner unless explicitly stated otherwise.

**Comment by thomasfanell** [comment]
Good! I always hated that thing.

**Comment by sebastianbaginski** [comment]
I guess there is no other way.

**Comment by marcusnaslund** [comment]
So it's decided. Good.

**Comment by davidhesselbom** [comment]
> Since string literals don't leak anymore

Cool, how'd you fix it?

**Comment by sebastianbaginski** [comment]
@davidhesselbom : https://github.com/magic-lang/ooc-kean/blob/develop/source/system/string/string_literal.c :/

**Comment by davidhesselbom** [comment]
Oh, I see. Glad you finally found a way, that thing bothered me to bits...

**Comment by marcusnaslund** [comment]
Everything but `Text` itself is gone now. It will disappear with #1835 , so closing this.
