### ISSUE TITLE
Automatic free of strings

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1763]
#1760 introduces very ugly code in `DateTime toString` and `TimeSpan toString` because of repeated `replaceAll` calls, where the intermediate string must be freed after each call.

We should implement some kind of automatic freeing for Strings. Two alternatives exist:

1) Besides `replaceAll`, add a `replaceAllAndFreeOriginal` (but with better name) which calls the former and then frees the original before returning.
2) Add a `Bool` argument to relevant functions, defaulted to false, which if true frees the current object.

This would also be nice for `print` and `println`, for example.

**Comment by thomasfanell** [comment]
I vote for option 2.

**Comment by sebastianbaginski** [comment]
3) Adapt `String` to use `give / take`

**Comment by davidpiuva** [comment]
I vote for 2.

**Comment by fredrikbryntesson** [comment]
2

**Comment by marcusnaslund** [comment]
> 3) Adapt `String` to use `give / take`

You're drunk, go home.

**Comment by marcusnaslund** [comment]
2 it is. Thanks people.
