### ISSUE TITLE
Freeing String literals

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1764]
Right now, calling `free` on a string literal will cause a segfault.

There should be a check in `free` to check whether the current object is a literal, and if so, not do anything. The `String` cleanup should be the only one which can free the string literals, perhaps via setting a "secret" flag in the `String` instance.

This will allow us to do stuff like `"literal" & variable` without problems. (Right now `"literal" << variable` must be used to not leak).

**Comment by sebastianbaginski** [comment]
>  calling free on a string literal will cause a segfault.

How do I reproduce ? This does not crash
```ooc
use base

x := "test"
x free()

"a" free()

GlobalCleanup run()
```

**Comment by davidpiuva** [comment]
Literals can be freed but they are only created once. Running a function with `"a" & "b"` should crash on second execution.

**Comment by sebastianbaginski** [comment]
Ok, thanks.
