### ISSUE TITLE
Implement sorted container with custom comparator

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1779]
Should support custom generic comparators.

A balanced binary search tree as backend would be nice.

**Comment by bettinaselig** [comment]
For example to have a start index as input at which one expect that the object is saved.

**Comment by marcusnaslund** [comment]
I think we'd be all right for now with a `SortedVectorList<T> extends VectorList<T>` which automatically calls `sort` upon `add`/`append`, what do you say @sebastianbaginski ?

**Comment by sebastianbaginski** [comment]
I guess it could be ok for now. It could also use the existing `upper / lowerBound` for searching.

**Comment by marcusnaslund** [comment]
The `SortedVectorList` as described above has made it to `develop` now. Waiting on the merge of `primaryFeature1.4` so that it can be optimized before I close this.

**Comment by marcusnaslund** [comment]
On second thought we don't have any need for optimization at the moment. And with the "...root of all evil" quote in mind I am closing this.

**Comment by marcusnaslund** [comment]
Taking this back, I'd like to add the simple optimization of checking whether the item is larger than the last (just append) or smaller than the first (insert at 0).

**Comment by marcusnaslund** [comment]
And closing again. Rock wouldn't exactly cooperate, and it wasn't worth the trouble.
