### ISSUE TITLE
Color distances are not euclidean...should they be?

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1827]
And some look plain wrong.

Most seem to suffer from a pair of missing parentheses, as is the case for `ColorUv`, `ColorYuv`, `ColorRgb`:
`((this u - other u) as Float pow(2) + (this v - other v) as Float pow(2)) / 2.0f sqrt()`
should be
`(((this u - other u) as Float pow(2) + (this v - other v) as Float pow(2)) / 2.0f) sqrt()`

The error in `ColorRgba` is even more severe. Currently it is:
`(this toRgb() distance(other toRgb()) * 3.0f + (this a - other a) as Float pow(2)) / 4.0f sqrt()`
but should be
`((this toRgb() distance(other toRgb()) pow(2) * 3.0f + (this a - other a) as Float pow(2)) / 4.0f) sqrt()`

Finally, `ColorYuva` has no distance method at all.

**Comment by marcusnaslund** [comment]
If you're working on that `Metric` class you should also be aware of this. @sebastianbaginski

**Comment by sebastianbaginski** [comment]
I'm not working on `Metric` now, but this is a quite a mess too :/
