### ISSUE TITLE
ToString does not work for negative TimeSpans

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1836]
~~Is there some logic to this difference, is it legacy from converted old C# code, or is it just an oversight that should be fixed?~~

ToString() only works for positive `TimeSpan`s at the moment.

If the ticks in `DateTime` would change to also be signed, we need the same fix there as well.

**Comment by marcusnaslund** [comment]
@emilwestergren @thomasfanell do you know?

**Comment by sebastianbaginski** [comment]
I think it makes sense to have a negative `TimeSpan`, that's why it's signed.

**Comment by emilwestergren** [comment]
I think it's from the definition of ticks, "number of nanoseconds/100 since 1/1/1". It means you can't have a date before that so it's always positive. A TimeSpan however can be negative.

I think we should use signed for both though, since we are moving away from forcing the use of ticks.

**Comment by marcusnaslund** [comment]
In that case, the `toString` method for `TimeSpan` is broken, since it cannot handle negative ticks.

**Comment by marcusnaslund** [comment]
I can understand that it might be **practical** to have a negative timespan sometimes. But is it always clear that a time *span*, as in a *length of time*, can be negative? I would never expect a geometric length to be negative, although components of a vector might.

**Comment by emilwestergren** [comment]
I think this is one of the reasons:
```ooc
unknownTimespan := calculation()
newTime := oldDateTime + unknownTimespan
```
This will work no matter if we go back or forward in time.

**Comment by sebastianbaginski** [comment]
@marcusnaslund  TimeSpan was meant to be more like a `time offset` ( a `ptrdiff_t` for two time points ).

**Comment by marcusnaslund** [comment]
Alright, thanks for the explanations. I will maintain that it's practical, but not neccessarily sensical.

This still means that `toString` is broken, so will update the issue accordingly.
