### ISSUE TITLE
(Re)implement ThreadPool::waitAll()

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1906]

**Comment by marcusnaslund** [comment]
@emilwestergren Should `waitAll()` return when the pool has finished all currently (at the time of the `waitAll` call) existing tasks, or return when the queue is empty *and* all jobs are completed (which may not be the same event if another thread keeps adding jobs)?

**Comment by emilwestergren** [comment]
Good question. For the main use case both should work but things get more complicated when you allow several threads to use the pool. In that case I guess it's not very useful to use `waitAll` since you don't really know what the queue contains at the moment (some other thread could have added stuff before you). Maybe it's better if `waitAll` waits until the pool is 100 % inactive. In this case you can use it instead of promise-loop if you know you're the only user. I accept `waitAll` is not a perfect solution, but for our specific case the code becomes so much cleaner. If you have a better idea how to solve this case then feel free to suggest it.

```ooc
promises: Promise[count]
for (i in 0 .. count)
   promises[i] = pool getPromise(f)
...
for (i in 0 .. count)
   promises[i] wait() . free()
```

```ooc
for (i in 0 .. count)
   pool add(f)
...
pool waitAll()
```

**Comment by emilwestergren** [comment]
Another option:
```ooc
promises := VectorList new(count)
for (i in 0 .. count)
   promises add(pool getPromise(f))
...
ThreadPool waitAll(promises)
```

**Comment by sebastianbaginski** [comment]
`waitAll()` does not have to be a function on `ThreadPool`. Looks like a set of promises could use a separate class, like `TaskCollection` or something, so you could just wait on a specific subset of promises from the pool.

**Comment by emilwestergren** [comment]
Like this?
```ooc
promises := PromiseCollection new()
for (i in 0 .. count)
    promises add(pool getPromise(f))
...
promises wait() . free()
```

Didn't someone implement something like this before?

**Comment by sebastianbaginski** [comment]
> Didn't someone implement something like this before?

Maybe :)
As for the api, I'd bind the PromiseCollection with thread pool:
```ooc
promises := PromiseCollection new(threadPool)
for (i in 0 .. count)
    promises add(f) // run `getPromise` internally
...
promises wait() . free()
```
but either way looks fine.

**Comment by marcusnaslund** [comment]
> Didn't someone implement something like this before?

Yes, I implemented a `PromiseCollector` a while back with that kind of functionality.

```ooc
promise := threadPool getPromise(f)
// or promise := Promise empty
for (i in 0 .. count)
    promise += threadPool getPromise(f) // creates a linked list of promises
promise wait() // waits until every promise in the chain returns
```

But it was tricky getting the memory management to work (this was of course in my early ooc days, so maybe it's not a big problem after all) and it didn't work with `Future`s (since they share a common `_Synchronizer` base class now, that may be easier to fix).

Noone used them though, and eventually they were scrapped.

**Comment by emilwestergren** [comment]
That looks clean, you can try to implement it and if it gets tricky fall back to one of the above "Promise-collection" solutions.

**Comment by marcusnaslund** [comment]
So you prefer manually building a chained list of `Promise`s over triggering a `WaitCondition` when the threadpool is inactive?

**Comment by emilwestergren** [comment]
Yes, it's closer to what we already have, and as you pointed out above, `waitAll` would get some nasty undefined behaviour for some cases. All I want is a cleaner way of adding tasks and then immediately wait for them all to finish, since it's such a common use case.

**Comment by marcusnaslund** [comment]
Alright, I'm on it.

**Comment by marcusnaslund** [comment]
Since operators aren't inherited, I'm going for

```ooc
promises := Promise empty // just a dummy promise
for (i in 0 .. count)
    promises chain(threadPool getPromise(f)) // creates a linked list of promises
promises wait() . free() // waits until every promise in the chain returns, then frees all of them
```
