### ISSUE TITLE
VectorList resizes with a constant increment each time

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#1980]
From `VectorList.ooc` (two places):

```ooc
if (this _vector capacity <= this _count)
	this _vector resize(this _vector capacity + 8)
```

We should investigate what the reason is for this and if we should change `+8` to something more common, like `*1.5` or `*2` (https://en.wikipedia.org/wiki/Dynamic_array#Growth_factor) if it doesn't have any performance impacts on other projects.

**Comment by sebastianbaginski** [comment]
Common use case is also `*2` until some threshold and then `+1024` or `+2048`, seems to work well.
