### ISSUE TITLE
Fixture has problems with is not equal, is not not true, etc.

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#539]
This seems to be an old problem, but why it happens remains a mystery. The following expect calls do not work:
```ooc
this add("true is not equal to(false)", func { expect(true, is not equal to(false)) })
this add("true is not not true", func { expect(true, is not not true) })
```
But the following does work:
```ooc
notEqualToFalse := is not equal to(false)
this add("true is not not true", func { expect(true, notEqualToFalse) })
notNotTrue := is not not false
this add("false is not not false", func { expect(false, notNotTrue) })
```
A big difference is that, in the latter case, `notEqualToFalse` and `notNotTrue` are resolved before the current test class is even initialized. Otherwise, they are resolved in the `add` call. The error message is as follows:
```error call expect(true, Fixture __getis__() __getnot__() __getnot__() __gettrue__()) waiting on static Fixture expect(value: Object, constraint: Constraint) to resolve.```

**Comment by marcusnaslund** [comment]
A simple way to fix this issue would be to, in addition to the normal `equal`, `greater` and `less` properties:

- ...add a `notEqual` property (instead of `not equal`)
- ...remove the `not` modifier completely

We should also add these two properties:

- `greaterOrEqual`
- `lessOrEqual`

The `not not` case seems like something we might just ignore.

What do you think @thomasfanell ?

**Comment by thomasfanell** [comment]
I think the unit framework needs a major overhaul, but for now, this is a good idea.

**Comment by marcusnaslund** [comment]
Indeed, but this would improve things a bit. I'm on it.

**Comment by marcusnaslund** [comment]
So, after #1452 , what should be done is

- [ ] Implement `greaterThanOrEqual`, `lessThanOrEqual` keywords
- [ ] Utilize the equality/inequality methods on float point numeric types instead of the current hack solution
- [ ] Fix correct output when tests using `is Null` and `is notNull` fail.
