### ISSUE TITLE
FloatMatrix: reuse allocated memory

### ISSUE THREAD

**Issue by davidhesselbom** [magic-lang/ooc-kean#579]
In `FloatMatrix`, instead of creating a new instance to store the result of e.g. `transpose` and freeing the original data, reuse the original data.

Also, if transposing a 1-dimensional `FloatMatrix`, just swap `this size` and return.

**Comment by sebastianbaginski** [comment]
I think it would make sense to create special cases for 4x4 and 3x3 matrices (or just one of them, depends which one is used most) with statically allocated data. This way you can escape the overhead introduced by dynamic memory allocation and owned buffer management for the case which is used most often. Dedicated structure with fixed size memory allocated on stack can be heavily optimized by the compiler as it knows the total size of the structure at compile time, for example all methods that iterates through elements of the matrix, as the number of elements in known during compilation.
I know (think?) that performance of the Matrix class is currently not a problem, but I think this is not totally stupid idea (at least Qt does that, they have *3x3*, *4x4* and *generic matrix* classes).

**Comment by niklasborwell** [comment]
I checked the number of elements in different cases. As far as I know, we are using this in two places, the estimator and the quaternion mean calculation. Apart from one step of the quaternion mean, it seems we basically only use odd sizes like 4x6, 1x6, 4x46(!), etc. The size varies in the estimator depending on some parameters and which model us used. So although I would love to have simpler matrix classes, I don't think they would be very useful for us right now. Unless I missed something.

**Comment by sebastianbaginski** [comment]
I like the 4x46 case, maybe we should hard-code this one :)
Thanks, nice to know the typical use cases. I guess we can come back to this idea if needed in the future.

**Comment by niklasborwell** [comment]
Oh yeah, actually we only have one ransac model right now that solves an equation system, but that might change. Also the parameters in that class control the size of the matrix used.

**Comment by tomasmahlberg** [comment]
The only place where we call `transpose` and also want to free the calling object is in `Quaternion weightedMean`, where it 98% of the time is a vector. I will do a PR for this special case where we just want to swap the dimensions.

I have not looked at any other methods(operators, as I was thinking this doesn't have high priority at the moment?

**Comment by davidhesselbom** [comment]
It doesn't have high priority, no.

**Comment by tomasmahlberg** [comment]
Then maybe we should also move it from PR debt to the Later milestone?

**Comment by marcusnaslund** [comment]
Is this really useful for us?
I mean, it's an idea for possible improvement, sure, but that doesn't it it warrants having an issue. Are we interested in doing anything about it? Otherwise, I vote we close this.

**Comment by niklasborwell** [comment]
Sounds like over-optimization. If we have an issue with this, it will pop up later, but most likely it won't. Close!
