### ISSUE TITLE
VSCode integration.

### ISSUE THREAD

**Issue by simonmika** [magic-lang/ooc-kean#588]
Today it is possible to build and run the tests by pressing `Ctrl-Shift-B`. If there are build errors and build warnings they will show up in error list.

This does still not work:
* [x] Warnings and errors in the test code does not link to the right path, problem with the source path in the use files.
* [x]  Magic should be run before building.
* [x]  Magic warnings should show up in the error list.
* [ ] Failed tests should show up in the error list.
* [ ] Code coverage integration using VS Code extension and coverage script.

**Comment by simonmika** [comment]
@thomasfanell: can you look at this.

**Comment by thomasfanell** [comment]
I just saw this. I'll look into it.

**Comment by thomasfanell** [comment]
magic is now able to host the build process and relay output from stdout and stderr to VS Code. However, since rock is inconsistent in the way it reports file paths, we have to modify it to output absolute paths upon errors/warnings, if we want to avoid hack-solutions.

**Comment by marcusnaslund** [comment]
What's the status on the final item here?

**Comment by thomasfanell** [comment]
Unfortunately the VS Code integration has been pushed into the background a bit lately. I'll give this a wee bit higher priority this week.

**Comment by marcusnaslund** [comment]
Let's add code coverage integration to this list as well, seems to work well with https://marketplace.visualstudio.com/items/bradleymeck.codecover and our `tools/codecoverage.sh` script.

**Comment by thomasfanell** [comment]
@marcusnaslund added to list

**Comment by marcusnaslund** [comment]
Thanks. To make it work, the extension requires a `json` file that specifies where the `.info` file generated by the code coverage script is located and where the source is. I wanted to put this in the `.vscode` folder, but it doesn't seem to work. I will try some more. Otherwise, it will end up in the root.

**Comment by marcusnaslund** [comment]
Any news here @thomasfanell @fredrikbryntesson ?

**Comment by thomasfanell** [comment]
@marcusnaslund Yes, i've been working on the build system a bit and made some progress. My hope is that we'll have a somewhat working version on Friday or possibly after the weekend, although I can't promise that.

**Comment by marcusnaslund** [comment]
Closing this as it isn't directly related to kean and we have a new system for dealing with issues/tasks like this.
