### ISSUE TITLE
Rewrite SynchronizedQueue and BlockedQueue

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#646]
There has for a long time been something wrong with the implementation of `BlockedQueue` (and possibly `SynchronizedQueue`) which seems to manifest itself more often in Windows than Linux, for some reason. This is the reason why the ThreadPool test hangs sometimes on CircleCI (and more often on AppVeyor).

**Comment by marcusnaslund** [comment]
We use `PRInt` instad of CircleCI nowadays, but there are still problems if the computer if there's a lot more going on - suggesting there are some race conditions.

**Comment by thomasfanell** [comment]
`SynchronizedQueueTest` fails 100% if `clang` is used, rather than `gcc`.

**Comment by fredrikbryntesson** [comment]
@sebastianbaginski Did your static analysis help us anything with this issue?

**Comment by sebastianbaginski** [comment]
Nope, nothing related to threading was reported.

**Comment by sebastianbaginski** [comment]
I guess we have to go with pencil + paper + debugger + lots of print statements, like good old days.
