### ISSUE TITLE
Move system/threading to source/concurrent

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#659]
There is only one obstacle in the way: `Exception`. It uses `ThreadLocal` to handle exceptions from different threads. (It's unclear whether this actually works.)

Unfortunately, moving the folder out and putting `use ooc-threading` in `Exception.ooc` causes a circular dependancy.

**Comment by sebastianbaginski** [comment]
Can't we move `Exception` out from sdk as well ?

**Comment by marcusnaslund** [comment]
It's used in over 30+ files in the sdk. If we removed all the exceptions the SDK could throw, though, then yes.

**Comment by sebastianbaginski** [comment]
Hmm. I think `ThreadLocal` is there to let each thread have it's own stack frame buffer to manage exceptions. If we change this to one global stack frame list, then we will have to somehow mark each stack frame and exception with thread id. Now each thread can process its own exception at the same time, if we remove `ThreadLocal` then all threads will have access to the same global stack frame buffer.
And then, we will need a mutex:)

**Comment by sebastianbaginski** [comment]
> It's used in over 30+ files in the sdk.

Let's assume you moved the Exception.ooc out from sdk. Can you make each of those 30+ files include the Exception class from this new file path ?

**Comment by marcusnaslund** [comment]
> Can you make each of those 30+ files include the Exception class
No, that will definitely be circular.

However, instead of `use ooc-threading` in `Exception`, can we do the slightly more ugly `import ../../threading/Thread`? If so, we could do it.

**Comment by marcusnaslund** [comment]
We will also be able to move `source/sdk/os/Process.ooc` + the two corresponding native classes. I think these might belong in the same folder.

**Comment by marcusnaslund** [comment]
Update: Because `Exception.ooc` has `import threading/ThreadLocal`, which in turn uses most other things in `sdk/threading`, no `sdk/threading` files can be moved out to `source/concurrent`. 

Without eliminating this dependancy, there seems to be no way of making this happen.

**Comment by marcusnaslund** [comment]
The only file(s) that can be moved belong to `WaitCondition`. An option is to move them to `source/concurrent` and then feel happy enough.
