### ISSUE TITLE
Keyboard / mouse input

### ISSUE THREAD

**Issue by davidhesselbom** [magic-lang/ooc-kean#660]
It is sometimes useful to have keyboard and mouse input for various reasons. Most of the work to enable this has already been done, so all that remains is to make it easier to register keys and buttons and their actions.

This works:
```ooc
	keyPressEvent := Event1<Key> new(func(key: Key) { })
	keyPressEventP := keyPressEvent&
	keyReleaseEvent := Event1<Key> new(func(key: Key) { })
	keyReleaseEventP := keyReleaseEvent&

... 

// a loop, somewhere	
	while (XPending(window _native display)) {
		event: XEventOoc
		XNextEvent(window _native display, event&)
		if (event type == KeyPress) {
			key: ULong
			key = XLookupKeysym((event xkey)&, 0) as ULong
			keyPressEventP@ call(key as Key)
		}
		if (event type == KeyRelease) {
			key: ULong
			key = XLookupKeysym((event xkey)&, 0) as ULong
			keyReleaseEventP@ call(key as Key)
		}
	}

	keyPressEvent = keyPressEvent add(func(key: Key) {
		if (key == Key Space)
			// do something
		else if (key == Key LeftControl)
			...
	})
	keyPressEventP = keyPressEvent&
```

... but obviously, this is messy. I propose an `InputHandler` class that belongs to a `window` that has a dictionary of keyboard keys or mouse buttons coupled with a `func` and and that is used like this:
```ooc
key := Key Space
window registerKeyPressEvent(key, func {
	// do something
})
```
and the loop described above checks, for each event (key press) in the queue, whether it exists in our dictionary, and if so, calls the function, effectively hiding all the stuff in the first code block inside a class.

**Comment by sebastianbaginski** [comment]
Good idea.
Maybe we can abstract it even futher with an `EventLoop` class that will be implemented both on windows and unix to handle the native even loop for the whole application. I was thinking about it since https://github.com/cogneco/ooc-kean/pull/607 , as the X11 window could really use the native event dispatch mechanism.

**Comment by davidhesselbom** [comment]
However we solve this, it needs to be platform independent. Have you been doing this sort of thing before?

**Comment by sebastianbaginski** [comment]
I have been using event loops heavily when programming with Qt, and as I'm curious how things are done, I have been reading some Qt source code too. It is not an easy task, but surely doable.

**Comment by davidhesselbom** [comment]
Alright. The above code is the only way I know how to do it in X11 (and I've read a lot of criticism about how bad that library is, but that's not my fault). If you have a better solution, I'm all ears.

**Comment by sebastianbaginski** [comment]
If you can work something out for @bettinaselig for unix then you probably should, as it will be faster than my idea of creating the events, event loops, dispatchers etc. hierarchy of classes. But I think it could be really nice to have it anyway. In the meantime, I can start working on the event abstractions.

**Comment by davidhesselbom** [comment]
I'd be happy to implement this myself, but 1. I need @simonmika to tell me if he has a better idea and 2. I don't have time right now, so Bettina will most likely be the one who ends up having to do it.

**Comment by sebastianbaginski** [comment]
OK, I think I can come up with something simple, just for mouse handling for now.

**Comment by simonmika** [comment]
@sebastianbaginski: can you fix this temporary and then solve it once and for all as an extension of the draw cleanup.

**Comment by sebastianbaginski** [comment]
Sure.

**Comment by marcusnaslund** [comment]
`sebastianbaginski was unassigned by davidhesselbom 7 days ago`, interesting.

Anyway, isn't this working now?

**Comment by sebastianbaginski** [comment]
yes, it works, you can capture key events with ascii codes
it can be updated later if something more advanced is needed
