### ISSUE TITLE
Safer transform of FloatBox2D

### ISSUE THREAD

**Issue by davidpiuva** [magic-lang/ooc-kean#749]
In case of rotating a square 45 degrees, the existing multiplication between FloatTransform2D and FloatBox2D will result in a flat rectangle with no area. Make a transform function that takes a center point, a circle radius and a transform to apply.

Alternatives:
* Just return the FloatBox2D bound of the resulting transformed circle.
* Take a (point, radius) touple and return a (point, radius) touple that can be given as argument to a FloatBox2D constructor.
* If enough methods can use a point with radius then a circle cover can be created replacing the touple but that is over-engineering for now.

**Comment by marcusnaslund** [comment]
In the PR linked above, while others seemed concerned, @bettinaselig said: 

> In my eyes, it is not critical if the size bounds are a bit wrong.

And that was two months ago. Is this still something we can/should/will fix?

**Comment by davidpiuva** [comment]
It can be fixed when someone uses the function with 45 degree rotation or someone has the time to fix it.

**Comment by bettinaselig** [comment]
I think the place where I use this the transform only includes translation. It is good if this is fixed, but it is not critical right now.

**Comment by davidpiuva** [comment]
It seems like FloatBox2D does not have a transform any more so there is nothing to fix.
