### ISSUE TITLE
Implement non-blocking free in ThreadPromise and ThreadFuture

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#754]
Right now, `free()` blocks until the thread finishes. We should (if asked for) set a `freeOnCompletion` flag instead which is checked when the thread finishes, which would then take care of freeing the object.

**Comment by marcusnaslund** [comment]
@emilwestergren is this something we want? If so, how should we do it?
Implement a `freeNoWait()` method?

**Comment by marcusnaslund** [comment]
I realize now that our `wait() . free()` for every `Promise`/`Future` is quite unneccessary, it's equal to (but maybe not as clear) to just call `free()`.

**Comment by emilwestergren** [comment]
Yes, but I don't think `wait` should be inside `free`. What about a `freeOnCompletion` mechanic?

**Comment by marcusnaslund** [comment]
> What about a freeOnCompletion mechanic?

Yes. But should it always do that, or should we also have a blocking free?

**Comment by emilwestergren** [comment]
I don't think we need a blocking free. If the user *must* wait before free, then why not just call wait before you free? :)

**Comment by marcusnaslund** [comment]
> I don't think we need a blocking free. If the user must wait before free, then why not just call wait before you free? :)

Good point. I will fix this.
