### ISSUE TITLE
Write tests for, and fix memory leaks in, source/net

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#757]
The contents of `source/net` are basically just copied from the original sdk and cleaned up to make magic happy. We do not even know if it works since we have never used it and there are no tests. Furthermore, there are most likely several memory leaks and unnecessary dependencies on what's left in the SDK.

Here is what should be done to solve this issue:

- [x] Implement rudimentary tests for what we want to do with the `net` classes
- [x] Verify that the `net` module works as expected and has everything we want for now
- [ ] Reduce memory leaks from the tests (and thus from relevant `net` classes) to zero

More sophisticated tests will follow in a later issue if/when we need it.

**Comment by marcusnaslund** [comment]
Related: https://github.com/fasterthanlime/rock/issues/814 which makes this issue deserve the `bug` label.

**Comment by sebastianbaginski** [comment]
@simonmika can we implement new version of this as extension to the new IO module ? I think sockets fit into the IO component anyway

**Comment by simonmika** [comment]
Yes, thats what we should do.

**Comment by marcusnaslund** [comment]
Updated with a slightly better description of what's needed. @fredrikbryntesson

**Comment by marcusnaslund** [comment]
Should be quite easy to take the examples from https://ooc-lang.org/docs/sdk/net/ and turn into basic tests, connecting the sockets to `localhost`.

**Comment by marcusnaslund** [comment]
@fredrikbryntesson Can we tick off the first box?

**Comment by marcusnaslund** [comment]
Regarding memory leaks (running the net tests):
```
definitely lost: 1,224 bytes in 49 blocks
indirectly lost: 21,672 bytes in 150 blocks
possibly lost: 0 bytes in 0 blocks
```

**Comment by fredrikbryntesson** [comment]
I can check how we can free the sockets better, and yes tick off the first.
