### ISSUE TITLE
Wrap C memory routines inside the Buffer class

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#763]
~~Even though we don't use GC, we still use `gc_free()` (as defined in `sdk/lang/Memory.ooc`) to not confuse the function with the regular `free()` we use on classes.~~

~~The names starting with `gc_` are a bit misleading, but more than just renaming them to something else, we should wrap `malloc`, `calloc` and `free` in some object-oriented way. Either by extending the `Pointer` class or by making a new `Buffer` implementation.~~

---
**Update (2016-01-28):**

- [x] Add a `moveTo` function wrapping `memmove`
- [x] `malloc`, `calloc`, `free` calls shall later utilize the `Buffer` class in `sdk/Buffer.ooc`. 
- [x] Verify that `malloc` etc. actually return something under the `safe` flag.

**Comment by marcusnaslund** [comment]
Making a note here: There should also be a `moveTo` function wrapping `memmove`.

**Comment by marcusnaslund** [comment]
With #1112 we now have `sdk/Buffer`. Let's make sure we also use it.

**Comment by davidpiuva** [comment]
With our own memory manager, we could make assertions that pointers are valid before use in the `-Dsafe` version.

**Comment by marcusnaslund** [comment]
Can we do something like this? We introduce a version flag `-DdebugMemory`:
```ooc
version (!debugMemory) {
    malloc: extern func (SizeT) -> Pointer
    free: extern func (Pointer)
    // etc. etc.
} else {
    _malloc: extern (malloc) func (SizeT) -> Pointer
    malloc: func (size: SizeT) -> Pointer {
        result := _malloc(size)
        "allocated %p" printfln(result)
        result
    }
    _free: extern (free) func (Pointer)
    free: func (pointer: Pointer) {
        "freeing %p" printfln(result)
        _free(pointer)
    }
```
That way, we don't always get an unneccessary function call for each allocation/free.
