### ISSUE TITLE
Cleaning up Color

### ISSUE THREAD

**Issue by davidpiuva** [magic-lang/ooc-kean#781]
- [x] Comparing equality with colors of other types only makes sense with classes.
- [x] `Set` can not be safely applied to covers since it is not a reference type.
- [x] Colors have more constructors than needed.
- [ ] The `Distance` function might be incorrect for BGRA since the BGR distance is not squared and applies some weird scaling instead.
- [x] Default values for UV can not be 0 since it gives negative intensity on some wavelengths.

**Comment by davidhesselbom** [comment]
Also, this:
> // FIXME: yuvToBgr2[512..end] and yuvToBgr2[256..511] are all 0, so there's some minor room for optimization here.
	// Also, since multidimensional arrays work now, the arrays below can be reorganized if so desired.

**Comment by marcusnaslund** [comment]
> Comparing equality with colors of other types only makes sense with classes.

How do you mean?

> Set can not be safely applied to covers

We do similar things in many covers, especially in `source/math` and `source/geometry`. What's wrong here?

>  Colors have more constructors than needed.

We should at least be consistent with which arguments may be used to create a color. But having one for `Float` and one for `Double` is unnecessary, I believe, as rock should implicitly cast from one to the other.

> The Distance function might be incorrect

Looks strange to me too, but I'm no expert here. Do you know who wrote it?

> Default values for UV can not be 0

What should they be then?

**Comment by davidpiuva** [comment]
Who would call a non virtual function without sideeffects that always returns false?

Set methods change by reference to this but covers are value types so that any side effect is thrown away on a copy.

I dont know who wrote the distance function.

Default uv should be gray intensity since a signed -1..1 scale is stored in unsigned bytes.

**Comment by sebastianbaginski** [comment]
(2) fixed in https://github.com/cogneco/ooc-kean/pull/1232

**Comment by davidpiuva** [comment]
Removed (6) since colors don't have to contain other colors.

**Comment by davidpiuva** [comment]
Enough point have been solved for me to consider Color to be good enough and not worth having an issue about.
