### ISSUE TITLE
Transform2D and Transform3D covers are lacking in test coverage

### ISSUE THREAD

**Issue by marcusnaslund** [magic-lang/ooc-kean#788]
The following public methods and properties are never tested:

- [x] `FloatTransform2D`
setTranslation, setScaling, setXScaling, setYScaling, setRotation, skewX, skewY, reflectX, reflectY, toIntTransform2D, toString, createSkewingX, createSkewingY, createReflectionX, createReflectionY, determinant, rotationZ, isProjective, isAffine, isSimilarity, isEuclidian, isIdentity

- [x] `IntTransform2D`
setTranslation, skewX, skewY, reflectX, reflectY, toFloatTransform2D, toString, createSkewingX, createSkewingY, createReflectionX, createReflectionY, determinant, isProjective, isAffine, isIdentity

- [x] `FloatTransform3D`
setScaling, setXScaling, setYScaling, setZScaling, rotateX, rotateY, rotateZ, reflectX, reflectY, reflectZ, transformAndProject, transformAndProjectCorners, project, createReflectionX, createReflectionY, createReflectionZ, createProjection, referenceToNormalized, normalizedToReference

**Comment by thomasfanell** [comment]
@molhamkhalil is currently working on tests for `FloatTransform2D`.

**Comment by molhamkhalil** [comment]
* I have Postponed the testing of IntTransform2D.

**Comment by molhamkhalil** [comment]
Fixed FloatTransform in PR #1424

**Comment by marcusnaslund** [comment]
Final part fixed in #1433
