### ISSUE TITLE
Plot: New functionalities

### ISSUE THREAD

**Issue by bettinaselig** [magic-lang/ooc-kean#801]
The pull requests https://github.com/cogneco/ooc-kean/pull/663 and https://github.com/cogneco/ooc-kean/pull/664 offered new functionalities to the plot module.

These functionalities need to be discussed before the can be added to upstream.
@simonmika @davidpiuva @marcusnaslund @davidhesselbom

**Comment by simonmika** [comment]
Suggest an API.

**Comment by marcusnaslund** [comment]
@bettinaselig @davidpiuva This issue should be updated with an actual description of what should be done or otherwise closed.

**Comment by davidpiuva** [comment]
The plotter needs a complete rewrite from scratch for a clear abstraction between input and file format but this is not a priority at the time.

**Comment by marcusnaslund** [comment]
If that's the case, then this `new functionalities` issue is invalid?

**Comment by davidpiuva** [comment]
No, it is put on ice in the later milestone because we don't have time.

**Comment by bettinaselig** [comment]
So... does this issue need a better description?

**Comment by davidpiuva** [comment]
1. Delete everything
2. Design a new plotter divided into data objects, plot objects and svg file management

**Comment by bettinaselig** [comment]
:+1:

**Comment by niklasborwell** [comment]
I would strongly suggest to use an external library instead of re-writing it from scratch.

**Comment by davidpiuva** [comment]
If we can port it to ooc. I rather not link to a closed source component with bugs that we can't fix for something so trivial.

**Comment by marcusnaslund** [comment]
It we want do redesign everything is #806 valid, then?

**Comment by davidpiuva** [comment]
Yes

**Comment by marcusnaslund** [comment]
Why? I see no need to fix the things there if it will all be replaced later.

**Comment by davidpiuva** [comment]
To delete all is the fix.

**Comment by marcusnaslund** [comment]
Since the main solution seems to be 

> 1. Delete everything

I'm closing this and #806.

Feel free to create a new issue with *more specifics* on what should and needs to be done *when* there's a decision regarding it. Generic issues like this just linger on forever.
