### ISSUE TITLE
Plot: Design

### ISSUE THREAD

**Issue by davidpiuva** [magic-lang/ooc-kean#806]
The main problems with the existing SVG plotter are abstraction and encapsulation.
* Variables that can not be used from the outside are exposed in the interface.
* SVG specific color names are stored as strings outside of the SVG module. If we find another file format with new features for reading values from points and stuff, we might want to keep the plotter part independent of the file format like we did with OpenGL.

**Comment by marcusnaslund** [comment]
Closed with comment here: https://github.com/magic-lang/ooc-kean/issues/801#issuecomment-207555534
