### ISSUE TITLE
Some GpuImages have a channelcount, RasterImages have bytesPerPixel

### ISSUE THREAD

**Issue by davidhesselbom** [magic-lang/ooc-kean#823]
For example,
```ooc
OpenGLMonochrome: class extends OpenGLPacked {
	channelCount: static Int = 1
```
but there's no such variable in `OpenGLPacked` or any of its parent classes, which means you can't access the field without casting a parent class to the child class first.

Meanwhile,
```ooc
RasterMonochrome: class extends RasterPacked {
	bytesPerPixel ::= 1
```
but again, this variable is not accessible from any of the parent classes, and the name is not consistent between `Raster` and `Gpu` images.

**Comment by emilwestergren** [comment]
There is a difference here, a Monochrome can have 1 channel but 4 bytes per pixel. You are correct in both cases though that we probably should have both these members for every RasterImage (and GpuImage/CpuImage should inherit RasterImage).

**Comment by davidhesselbom** [comment]
Okay, there's a difference. It's not clear enough, though - it looks like a mistake to the uninitiated.

**Comment by niklasborwell** [comment]
@emilwestergren Relevant?

**Comment by emilwestergren** [comment]
Yes

**Comment by marcusnaslund** [comment]
Will you be looking at this as well @davidpiuva ?

**Comment by davidpiuva** [comment]
I think it is best to just explain the difference in code comments since bytes are abstracted away on the GPU.

**Comment by marcusnaslund** [comment]
You know better than me, I just want to know whether there's anything in code to do here or whether we can close this.

**Comment by davidpiuva** [comment]
You can close if it takes up visual space since it is not important to fix.

**Comment by marcusnaslund** [comment]
> just explain the difference in code comments

Do it if you think it's really neccessary (we seem to have survived without them for a long time), otherwise let's move on.
