### ISSUE TITLE
Use enum values instead of `true` and `false` for marking ownership

### ISSUE THREAD

**Issue by sebastianbaginski** [magic-lang/ooc-kean#891]
`ByteBuffer` and possibly other classes use boolean values to indicate ownership of underlying data backend. It could be more readable to use enum values instead.

**Comment by davidhesselbom** [comment]
Depends on how many states you have. I don't really see the point in a two-value enum...

**Comment by sebastianbaginski** [comment]
We already have an enum for this (in `OwnedBuffer` I think), so it's only a matter of using it.

**Comment by davidhesselbom** [comment]
`Owner` has 5 states. Is that the one you mean? In that case, alright, why not.

**Comment by sebastianbaginski** [comment]
Yeah I think so. `vector := FloatVector(32, Owner Sender)` is more readable to me than `vector := FloatVector(32, false)`.

**Comment by davidhesselbom** [comment]
Yes, I agree.

**Comment by davidhesselbom** [comment]
However, it still doesn't clarify what `Owner` refers to - the memory where the items are stored, or the items themselves (if they are Objects).

**Comment by sebastianbaginski** [comment]
That's true, there is still some ambiguity left.

**Comment by marcusnaslund** [comment]
Is this something for the architech group to discuss? @fredrikbryntesson @sebastianbaginski

**Comment by fredrikbryntesson** [comment]
Sure, I think Sebastian has some good points here.

**Comment by marcusnaslund** [comment]
Well, I agree that using `Owner Sender` and `Owner Receiver` isn't a great idea here.
Today's meeting sure didn't show overwhelming support, so do we really need to implement this?

**Comment by sebastianbaginski** [comment]
I don't really see a problem with a two-value enum used instead of `true / false`. 
But if both of you are fine with keeping the current code, then just close this issue. I can live with that.

**Comment by davidhesselbom** [comment]
How about two enums? E.g.
`vector := FloatVector(32, Owner Receiver, Owner Sender)` for when the vector owns the array of pointers, but not the objects pointed to. Or additional values in the enum to cover these cases. Of course, `Owner SenderOfContentsButNotData` looks dumb.

**Comment by marcusnaslund** [comment]
> `vector := FloatVector(32, Owner Receiver, Owner Sender)`

That looks just as confusing as `vector := FloatVector(32, true, false)` to me.

**Comment by marcusnaslund** [comment]
Will reopen if someone really screams out in favour of the `enum` solution, and can also present a viable one.

**Comment by davidhesselbom** [comment]
> That looks just as confusing as vector := FloatVector(32, true, false) to me.

Yeah, true. You'd really need two different enums (and make them non-optional) to be safe.
