### ISSUE TITLE
Vector2D is inconsistent with raster images.

### ISSUE THREAD

**Issue by davidpiuva** [magic-lang/ooc-kean#921]
`row, column` corresponds to `y, x` in raster images which can lead to confusion and bugs since people assume x before y alphabetically. An `IntVector2D size` would also make it easier to switch between raster images and Vector2D.

**Comment by davidpiuva** [comment]
Where Vector2D is iterated over using loops, having Y outside of X has no cache benefits if the access uses the incorrect [x, y] order instead of [row, column] that is used. For large 2D vectors not fitting into L2 cache, this can cause a computer to freeze for 200ms while caching things that are never used.

**Comment by marcusnaslund** [comment]
Isn't `FloatImage` the solution to this?

**Comment by davidpiuva** [comment]
Vector2D only uses `Int` and `UShort` at this time but improving Vector2D can remove the need for FloatImage.

**Comment by davidpiuva** [comment]
Solved by https://github.com/magic-lang/ooc-kean/pull/1773
