### ISSUE TITLE
Implement thread safe VectorList

### ISSUE THREAD

**Issue by emilwestergren** [magic-lang/ooc-kean#923]
`SynchronizedVectorList`?

**Comment by emilwestergren** [comment]
@marcusnaslund something you are interested in? :)

**Comment by marcusnaslund** [comment]
Sure! Is it urgent?

**Comment by emilwestergren** [comment]
Not really urgent but I have some code that can make use of it.

**Comment by marcusnaslund** [comment]
Do you need any specific things in it or just a `VectorList` with a mutex, pretty much?

**Comment by sebastianbaginski** [comment]
It could be possible to just add `Mutex` to our regular vector or vectorList and default it to `MutexUnsafe`. `MutexUnsafe lock / unlock` is a no-op, it will be optimized out completely with `-O2` or `-O3`. Just think about all the code duplication :( Maybe a MutexType could be another generic parameter like
```ooc
VectorList: class <T, MutexType> {
}
```
?

**Comment by emilwestergren** [comment]
Yes just a VectorList with a mutex. I agree Sebastian, it doesn't scale very well to implement this for every collection.

**Comment by emilwestergren** [comment]
@simonmika proposed to implement an abstract class `List` and concrete `SynchronizedList` which has a `List` as a backend. `SynchronizedList` can then be constructed with any implementation of `List`. This is how `Queue` has been implemented.

**Comment by marcusnaslund** [comment]
Fixed by #1248 which introduces `SynchronizedList` with a `VectorList` backend.

**Comment by emilwestergren** [comment]
So we can close this?

**Comment by marcusnaslund** [comment]
> So we can close this?

Sorry, I thought I did that. Will you or @christopherlagerhult implement it in `RecycleBin`?

**Comment by emilwestergren** [comment]
@christopherlagerhult can do it
